name: Update Markprompt Data

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_call:
  workflow_dispatch:

jobs:
  provide_repos_json:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout the repo B
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set Matrix
        id: set-matrix
        run: |
          REPOS=$(curl -s https://raw.githubusercontent.com/SovereignCloudStack/docs-page/main/docs.package.json | jq -r '.[] | .repo + " " + .source + " " + .label + " " + .target')
          echo "::set-output name=matrix::$REPOS"
  
  sync_repos:
    needs: provide_repos_json
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix: 
        repos: ${{ fromJson(needs.provide_repos_json.outputs.matrix) }}
    steps: 
      - name: checkout the repo B
        uses: actions/checkout@v2
        with:
          ref: main
  
      - name: clone repo A which is about to be synchronized
        uses: actions/checkout@v2
        with:
          repository: ${{matrix.repos.repo}}
          ref: main
          path: 'repo_to_be_edited'

      - name: remove git folders from A
        run: |
          rm -rf $(pwd)/repo_to_be_edited/.git

      - name: remove README.md files from A
        run: |
          find $(pwd)/repo_to_be_edited -name "README.md" | xargs rm -f

      - name: create subdirectory
        run: |
          mkdir $(pwd)/${{matrix.repos.target}}/${{matrix.repos.label}} || true

      - name: copy docs content from A to B
        run: |
          cp -r $(pwd)/repo_to_be_edited/${{matrix.repos.source}} $(pwd)/${{matrix.repos.target}}/${{matrix.repos.label}}
          
      - name: remove repo A
        run: |
          rm -rf $(pwd)/repo_to_be_edited/

      - name: update README.md with tree overview
        run: |
          tree -I '.git' >> README.md
          echo '' >> README.md
          echo '**NOTE:** This repository is only a snapshot of the files defined in the `docs.package.json` file for training purposes. Do **not** manually commit to this repository.' >> README.md

      - name: add and commit changes to B
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add --all
          git commit -m "Update docs for ${{matrix.repos.label}}"
          git push
