name: Update Markprompt Data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Get files
        run: |
          curl -s https://raw.githubusercontent.com/SovereignCloudStack/docs-page/main/docs.package.json \
          | jq -c '.[] | {repo: .repo, source: .source, target: .target, label: .label}' \
          | while read -r line; do
            repo=$(echo $line | jq -r '.repo')
            source=$(echo $line | jq -r '.source')
            target=$(echo $line | jq -r '.target')
            label=$(echo $line | jq -r '.label')
            git clone --depth 1 "https://github.com/$repo" "$repo"
            cd "$repo"
            if [ -z "$label" ]; then
              cp -r "$source" "../$target/"
            else
              cp -r "$source" "../$target/$label/"
            fi
            cd ..
            rm -rf "$repo"
          done
      - name: Update README
        run: |
          echo "# Markprompt Data" > README.md
          echo "" >> README.md
          echo "This repository contains the following files:" >> README.md
          echo "" >> README.md
          find . -type f ! -name README.md | sed 's/^\.\///' >> README.md
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update Markprompt Data"
          commit_options: "--no-verify"
